version: "3"

services:
  app:
    container_name: evodev-dockernode
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    image: webapp:evodev-dockernode